# Generated by Django 4.2.13 on 2024-07-02 09:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_price_orderitem_unit_price"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comment",
            managers=[
                ("ApprovedObjects", django.db.models.manager.Manager()),
            ],
        ),
    ]
