# Generated by Django 4.2.13 on 2024-07-07 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_category_top_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="inventory",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
